### PR TITLE
Filtering out script tags in messages

### PR DESCRIPTION
**Pull request by johndarv**

### CODE REVIEW

**Comment by meadsteve** [comment]
@johndarv I think your todo mentioned something like #18

**Comment by johndarv** [comment]
Ups didn't realise this was a duplicate. How do I remove it?

**Comment by meadsteve** [comment]
@johndarv not a duplicate. But you said
`TODO: Probably should start separating stuff into separate files`
Which I've now done.

**Comment by faroligo** [comment]
@johndarv this is good but will only sort script tags.  We might need to look at some more complete sanitisation that would pick up things like:

(https://gist.github.com/faroligo/6102aa7ddc3e4e8d8330)

**Comment by meadsteve** [comment]
@johndarv @Harxy @faroligo I still think the solution is to de-html all incoming messages. Then just add in fun crazyness using things like the gif me extension.

**Comment by Harxy** [comment]
I really don't want to de-html messages. I get why it would be a good idea but I love the versatility - soundcloud, youtube etc etc is all made possible by that

**Comment by meadsteve** [comment]
but we could just autodetect soundcloud links and magically wrap them in html.

**Comment by meadsteve** [comment]
And you could always re-enabled a subset of html after escaping it all. Obviously we'd want to keep the marquee tags working.

**Pull request merged**
