### PR TITLE
Added auto gif

### PR DESCRIPTION
**Pull request by faroligo**

### CODE REVIEW

**Comment by faroligo** [comment]
Bit rough and ready but works

**Comment by faroligo** [comment]
works by typing:
gif me KEYWORD into chat

**Comment by faroligo** [comment]
fixes #8

**Comment by meadsteve** [comment]
Can I request you rebase rather than "  Merge remote-tracking branch 'upstream/master'" @faroligo ?

**Comment by faroligo** [comment]
Yeah - I meant to rebase it all but forgot as have to rush into a meeting.  Do I have to close this and open a new pull request?

**Comment by faroligo** [comment]
Or can I change the existing?

**Comment by meadsteve** [comment]
I'd rebase the existing and force push to your branch

**Comment by meadsteve** [comment]
I find a sensible rule is you can rewrite git history on your branches but not on anything that someone else will depend on. Like the upstream master.

**Comment by faroligo** [comment]
I'll close this then otherwise it wont know how to compare when i push again

**Comment by meadsteve** [comment]
but otherwise: Good work :+1: I :heart:  this. @faroligo

**Pull request closed without merging**
