### PR TITLE
Fix & re-enable frontend tests

### PR DESCRIPTION
**Pull request by meadsteve**
Basically my suspicion was correct and the front end tests got stuck waiting for all the interval and timeout processes to end. I've made this all explicitly linked off of the close() call now:

``` js
        heartBeat.stop();
        playQueue.stop();
        bayeux.getClient().disconnect();
        bayeux.close();
        server.close();
```

we'll need to remember this each time we add anything that has an interval or timeout function.
#### UPDATE

Basically the in-process zombie made this all flakey and likely to break. I've replaced this with phantomjs being driven by selenium. But this does mean selenium needs to be running for the tests to work. Makes this much less portable as any machine running the tests will need java. But it is much more reliable.

### CODE REVIEW

**Comment by meadsteve** [comment]
hmmm something I merged in rebroke this. 
don't merge this just yet

**Comment by faroligo** [comment]
there is a conflict now anyway...

**Comment by meadsteve** [comment]
@faroligo no there isn't

**Comment by faroligo** [comment]
hmmm...

**Comment by meadsteve** [comment]
(I rebased)

**Comment by meadsteve** [comment]
Investigating a new approach:
upsides: it works, code is a bit neater as webdriverio is bette than zombie.
downsides: had to copy selenium in to the repo. it's made it a bit large.

@faroligo @johndarv @Harxy thoughts?

**Pull request closed without merging**
