### PR TITLE
Roomception me

### LINKED ISSUE #59: feature: roomcursion me #room
typing `roomcursion me #room` should insert and iframe pointing to that room into the room.

Thoughts?

### PR DESCRIPTION
**Pull request by meadsteve**
Fixes #59 
Typing either

```
roomcep me #hpynotoad
roomception me #hypnototoad
```

will embed the room in an iframe in that chat.

I've also taken this opportunity to tidy up the way functions are called in the auto html extension.

### CODE REVIEW

**Comment by Harxy** [comment]
Hey Steve I'm out of London until tomorrow, if you're happy, feel free to merge this to master yourself.

**Comment by meadsteve** [comment]
@Harxy not like we are in a rush. Anyone can review and merge later.
Thought you might be interested in the array of functions I used. It was something I mentioned you can do in js the other day.

**Comment by meadsteve** [comment]
@harxy you changed your mind? Thought you weren't keen?

**Comment by meadsteve** [comment]
ahh @Harxy hadn't seen fd585ce52c19b13c327b6a019a410afec7995542 . Was slightly surprised you'd merged it in the first place.

**Pull request merged**
