### PR TITLE
Room spy

### PR DESCRIPTION
**Pull request by meadsteve**
So I was reading up and playing about with faye this morning to see what's possible (in case we end up using this a bit more).

I've created some code that listens for subscription events then posts the rooms being joined in the rooms room. This is related to  #11 in that you'll be able to see users moving about. Though you won't actually see who they are.

### CODE REVIEW

**Comment by meadsteve** [comment]
Also generally speaking I think using the client from `bayeux.getClient()` would be a better way to implement our `dice me` and `gif me` features. The server could literally reply to them rather than just modifying the initial message.

**Comment by faroligo** [comment]
@meadsteve not sure I agree it's a better implementation as wouldn't really support chaining extensions together if we had individual bots.  Discuss tomorrow.

**Comment by meadsteve** [comment]
@faroligo but bots aren't really something you'd chain. When you type `gif me` you are requesting the server goes and gets you something based on the message content. That's a different category of action to the other extensions which modify the message in some way. The bots messages would still be processed by all the extensions. For example in this PR I've made use of the fact the `#roomname` gets turned in to a link by an extension.

**Comment by faroligo** [comment]
@meadsteve ok. Very true, I do like the fact the extension has the ability to suppress the original message though. On a related point I also thought we could get clients to also subscribe to a private messages version of the channel they are on so bots can send direct messages to users. _cant locate xxx_ etc.

**Pull request closed without merging**
